version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"


  backend:
    container_name: backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    links:
      - frontend:frontend
      - backend:backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Backend/certificate.crt:/etc/ssl/certificate.crt
      - ./Backend/private.key:/etc/ssl/private.key
    depends_on:
      - frontend
      - backend